install:
- wget https://raw.githubusercontent.com/jabooth/traviconda/master/traviconda.py -O traviconda.py
- python traviconda.py setup 2 --channel menpo
- export PATH=/home/travis/miniconda/bin:$PATH

script:
- python traviconda.py auto ./conda --binstaruser menpo --binstarkey $BINSTAR_KEY --pypiuser $PYPI_USERNAME  --pypipassword $PYPI_PASSWORD

notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/7599ff4870c99ba51310
    on_success: always
    on_failure: always
    on_start: never

