package:
  name: pcl
  version: 1.7.1

source:
  fn: pcl-1.7.1.tar.gz
  url: https://github.com/PointCloudLibrary/pcl/archive/pcl-1.7.1.tar.gz


requirements:
  build:
    - cmake [win]
    - eigen
    - flann
    - boost_python
  
about:
  home: http://pointclouds.org/
  license: BSD
